export enum WebsocketClientEvent {
  TEST_FLOW_RUN_STARTED = 'TEST_FLOW_RUN_STARTED',
  TEST_FLOW_RUN_PROGRESS = 'TEST_FLOW_RUN_PROGRESS',
  TEST_STEP_FINISHED = 'TEST_STEP_FINISHED',
  REFRESH_BLOCK = 'REFRESH_BLOCK',
}

export enum WebsocketServerEvent {
  TEST_STEP_RUN = 'TEST_STEP_RUN',
  TEST_FLOW_RUN = 'TEST_FLOW_RUN',
}
